spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liulibei/spring-cloud-study-config # 配置git仓库的地址
          search-paths: spring-cloud-study-config # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: liulibei
          password: a8325123
server:
  port: 12000